### PR TITLE
Allow labels for R and Rscript in toolchain

### LINKED ISSUE #87: r_toolchain to support setting r and rscript using Bazel target names/labels
I'd like to have r_toolchain r and rscript set using Bazel target names/labels to support Bazel itself providing R, like rules_nixpkgs, or even Bazel building R.

E.g.:

```
r_toolchain(
    name = "r_toolchain_linux",
    r = "@Rnix//:bin/R",
    rscript = "@Rnix//:bin/Rscript",
```

### PR DESCRIPTION
**Pull request by siddharthab**
Fixes #87.

### CODE REVIEW

**Comment by siddharthab** [comment]
Looks like this is ready to go. Try it out and let me know if it works for you.

**Comment by siddharthab** [comment]
I did some more testing since yesterday. It looks mostly OK. I am going to merge it, and if anything comes up in your testing, let me know and we can make another change.

**Comment by borancar** [comment]
Seems there's an issue with the build_*.sh scripts resolving the path, e.g.:
```
external/com_grail_rules_r/R/scripts/build_pkg_common.sh: line 87: @Rnix//:bin/R: No such file or directory
```

To verify, I'm using tag 0.8.4 which is tag after the change was merged, and the sha256 of the tar.gz artifact is 9c3823a75d1f15e64dc94401325f6e447bc8ad48e10761a06250ceaeeae3289d.

**Comment by borancar** [comment]
Ah, nvm - I'm being silly - just realized I should leave R out and only set Rscript.
EDIT: Sorry, no, that just tried to use R directly.

**Comment by siddharthab** [comment]
Maybe something wrong with how you are using it.

Can you check if this works:
```
cd rules_r
cd tests
# edit WORKSPACE to say `use_r_from_nix= TRUE`
bazel build //packages/exampleA
```

And then backtrack to see what you are doing different.

**Comment by siddharthab** [comment]
When I run things like above, my PATH during the builds becomes `/Users/sbagaria/.cache/bazel/fbcd335144c4da9c79038f9ce88e9f6d/sandbox/darwin-sandbox/12/execroot/com_grail_rules_r_tests/external/Rnix/bin:/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.`.

Can you check with `bazel build --features=rlang-debug //packages/exampleA` and look for a `export PATH=` statement?

**Comment by siddharthab** [comment]
Also, sorry, the title of this commit is actually misleading. We don't allow labels for `R` and `Rscript`. See where I mention nix in the README and follow the trail.

**Comment by borancar** [comment]
Yeah, I realized that in the meantime :man_facepalming:, but still didn't work. I'm now building the test to see if that works.

**Comment by borancar** [comment]
Yeah, after fixing other stuff, like missing as and rsync, exampleA compiles for me. I might submit a PR that handles the hermeticity case issues.

**Pull request merged**
