### PR TITLE
R image rule

### PR DESCRIPTION
**Pull request by hchauvin**
This is a continuation of the r_binary PR.  I put it in a different PR because I had to fork rules_docker until https://github.com/bazelbuild/rules_docker/pull/343 is merged and to change travis spec.

This PR adds an r_image rule, in the fashion other languages are featured in rules_docker.  This is not the solution I used for putting R scripts along with runfiles in Docker images, but this solution is more efficient as it allows the reuse of the container layers where R packages are put.

### CODE REVIEW

**Comment by siddharthab** [comment]
I think this particular feature is better placed in rules_docker as it relies on many details from there that are not well advertised and I am not sure if they are meant for public use. What I can do here is to provide a tar for the r_binary runfiles that can act as the final layer in the docker image. Like how we do for making images from r_library right now.

https://github.com/bazelbuild/rules_docker/issues/193

**Comment by hchauvin** [comment]
I haven't seen this issue, thanks.  Ok so I'm going to take it to rules_docker, that will be better indeed.

Concerning the tar for the r_binary, the whole idea of the dep_layer/app_layer is to avoid doing this for efficiency.

**Comment by hchauvin** [comment]
FYI here is what an r_image rule within rules_docker would look like: https://github.com/hchauvin/rules_docker/pull/1

I'll be testing that in the following days, to see how it holds.

**Comment by siddharthab** [comment]
I gave some time to understand app_layer and dep_layer, and have included your suggestions in this repo for now. We should still move the code to rules_docker because it can be maintained better there as app_layer and dep_layer are not advertised public interfaces and undergo breaking changes.

Please let me know if you are still interested in opening a PR in rules_docker.

https://github.com/grailbio/rules_r/blob/master/R/container/binary.bzl

**Comment by hchauvin** [comment]
Yes, that's a good idea, I'll update my PR draft (https://github.com/hchauvin/rules_docker/pull/1) to your latest changes.

**Pull request closed without merging**
