### PR TITLE
correctly assess the return code of buildifier

### PR DESCRIPTION
**Pull request by hchauvin**

### CODE REVIEW

**Comment by siddharthab** [comment]
I want to reproduce this. From where did you get your buildifier binary? I get a return code of 0 for in-place editing.

**Comment by hchauvin** [comment]
At HEAD: https://github.com/bazelbuild/buildtools/blob/82b21607e00913b16fe1c51bec80232d9d6de31c/buildifier/buildifier.go#L309

**Comment by siddharthab** [comment]
But we use the fix (default) mode. If you prefer, we can explicitly say fix mode.

**Comment by hchauvin** [comment]
Yes, this is not a relevant line, I wrote too fast. I must have an outdated version of Buildifier then, but somehow I could not track the commit it came from. Sorry for that!

**Pull request closed without merging**
